/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.*;
import gui.menu;
import java.awt.Dimension;
import static java.awt.Event.ENTER;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Leticia
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public login() {
        initComponents();
        setIcon();
        Dimension tamTela = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension tamJan = getSize();
          setLocation(new Point((tamTela.width - tamJan.width)/2,
          (tamTela.height - tamJan.height)/2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblUSUARIO = new javax.swing.JLabel();
        jLabelChavelLogin = new javax.swing.JLabel();
        lblSENHA = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(227, 245, 255));
        jPanel1.setLayout(null);

        lblUSUARIO.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUSUARIO.setText("Usuário:");
        jPanel1.add(lblUSUARIO);
        lblUSUARIO.setBounds(220, 100, 60, 20);

        jLabelChavelLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelChavelLogin.setText("Login");
        jPanel1.add(jLabelChavelLogin);
        jLabelChavelLogin.setBounds(280, 30, 70, 30);

        lblSENHA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSENHA.setText("Senha:");
        jPanel1.add(lblSENHA);
        lblSENHA.setBounds(220, 150, 60, 20);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo p.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 40, 200, 220);

        jTextFieldUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(280, 100, 150, 21);

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEntrar);
        jButtonEntrar.setBounds(210, 200, 80, 30);

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSair);
        jButtonSair.setBounds(350, 200, 70, 30);

        jPasswordFieldSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(280, 150, 150, 21);

        getContentPane().add(jPanel1);

        setBounds(0, 0, 470, 346);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
     if(jTextFieldUsuario.getText().equals("Elimar")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Jonatan")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Rubens")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Ruan")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Angel")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Antonio")&&jPasswordFieldSenha.getText().equals("1234")){
        menu tela = new menu();
        tela.setVisible(true);
        dispose();
    }                                              
        else{
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado!");
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
   System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
  if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        if(jTextFieldUsuario.getText().equals("Elimar")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Jonatan")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Rubens")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Ruan")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Angel")&&jPasswordFieldSenha.getText().equals("1234")
           ||jTextFieldUsuario.getText().equals("Antonio")&&jPasswordFieldSenha.getText().equals("1234")){
        menu tela = new menu();
                      tela.setVisible(true);
        dispose();
    }                                              
        else{
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado!");
        }
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelChavelLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel lblSENHA;
    private javax.swing.JLabel lblUSUARIO;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/icone.png")));
    }
}
